kind: network
metadata:
  name: main
spec:
  params:
    network_name: main
    project_id: local.alias_project.project_id
    subnets:
      - subnet_flow_logs: false
        subnet_ip: 10.1.0.0/16
        subnet_name: main
        subnet_private_access: true
        subnet_region: local.region
---
kind: project
metadata:
  name: main
spec:
  params:
    activate_apis:
      - compute.googleapis.com
      - container.googleapis.com
    billing_account: 111111-AAAAAA-222222
    create_project_sa: false
    default_service_account: keep
    disable_services_on_destroy: false
    folder_id: "1234567890"
    labels: {}
    name: prod
    org_id: "666"
    random_project_id: true
