name: Test
on: 
  pull_request:
    branches:
      - 'main'
    
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: npm install
      - name: Run Test
        run: npm test



